services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2017-latest
    container_name: mssql
    restart: always
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Monika@1407!
    ports:
      - 1433:1433
    networks:
      - mynetwork
    volumes:
      - ./msql_data:/var/opt/mssql
    expose:
      - "1433"


  postgres:
    image: postgres:14
    container_name: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: testdb
    ports:
      - "5432:5432"
    networks:
      - mynetwork
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

    expose:
      - "5432"

networks:
  mynetwork:

volumes:
    mssql_data:
    postgres_data:

